fix missing packages in organization when opening broken links page
  "packages": organization["packages"],
KeyError: 'packages'

ignore 'packages' when missing and do the same for 'description' and 'image_display_url'